# Site settings
title: Hao Zhong
subtitle: 
email: zhong5930@gmail.com
description: I am a software engineer at Capital One
#baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://leoz123.github.io/" # the base hostname & protocol for your site
author: Hao Zhong
street_address:
city:
state:
zip_code:
country:
phone:

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: https://www.facebook.com/leozhong123
github_url: https://github.com/LeoZ123
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/haozhong1234
pinterest_url:
slack_url: 
twitter_url:

# Build settings
markdown: kramdown

sass:
  style: compressed

future: true
timezone: UTC-5
